### PR TITLE
Fix the bot commenting on edits more than once

### LINKED ISSUE #12855: Bot posts on any edit instead of only posting once.
Type: code issue

### PR DESCRIPTION
**Pull request by strugee**
Note: this does the *bare minimum* to make tests pass. This change has no real test coverage, but this bug is causing real pain and I _did_ test it manually in production so it'll have to do for now. At some point I'll send a followup PR adding the missing coverage.

Fixes #12855

### CODE REVIEW

**Comment by cschanaj** [comment]
cc @Hainish @cowlicks

File: utils/issue-format-bot/lib/issueedit.js [hunk 1]
```diff
@@ -48,7 +48,34 @@ module.exports = function(robot, alexa) {
...
+        // before this conditional was put in place
+        if (comment.body.includes('HELPED_COMMENT_POSTED')
+            || comment.body.includes('Your edit helped me out')) {
+          commentedBefore = true;
+        }
+      });
+
+      if (commentedBefore) return;
+
+      const params = context.issue({body: 'Thanks! Your edit helped me out. I\'ll take it from here now. <!-- HELPED_COMMENT_POSTED -->'});
```
Comment (koops76) [inline utils/issue-format-bot/lib/issueedit.js]: `const params = context.issue({body: "Thanks! Your edit helped me out. I'll take it from here now. <!-- HELPED_COMMENT_POSTED -->"});`

File: utils/issue-format-bot/test/mocks/context.js [hunk 2]
```diff
@@ -22,6 +22,12 @@ module.exports = {
...
         issues: {
           createComment: sinon.spy(),
+          // TODO actually make this keep track of data
+          getComments: function() {
+            return {
+              data: []
+            };
+          },
           addLabels: sinon.spy(),
           removeLabel: sinon.spy(() => new Promise(noop))
```
Comment (koops76) [inline utils/issue-format-bot/test/mocks/context.js]: `removeLabel: sinon.spy(() => Promise.resolve())`?

File: utils/issue-format-bot/lib/issueedit.js [hunk 3]
```diff
@@ -48,7 +48,34 @@ module.exports = function(robot, alexa) {
...
+      //
+      // XXX handle the user screwing up, then fixing it (and getting
+      // the success comment), then screwing up again
+      const _allComments = await context.github.issues.getComments(context.issue({
+        per_page: 100, // eslint-disable-line camelcase
+        since: '2017-09-25'
+      }));
+      const allComments = _allComments.data;
+
+      allComments.forEach(comment => {
```
Comment (koops76) [inline utils/issue-format-bot/lib/issueedit.js]: `for (const comment of allComments) {`

File: utils/issue-format-bot/lib/issueedit.js [hunk 4]
```diff
@@ -48,7 +48,34 @@ module.exports = function(robot, alexa) {
...
+      let commentedBefore = false;
+
+      // This won't work if the bot comments success past 100 comments
+      // but since this will probably never happen, who cares. Also,
+      // the bot was originally put into production late September, so
+      // only ask for comments after then.
+      //
+      // XXX handle the user screwing up, then fixing it (and getting
+      // the success comment), then screwing up again
+      const _allComments = await context.github.issues.getComments(context.issue({
```
Comment (koops76) [inline utils/issue-format-bot/lib/issueedit.js]:
```
const allComments = (await context.github.issues.getComments(context.issue({
  per_page: 100, // eslint-disable-line camelcase
  since: '2017-09-25'
}))).data;
```

File: utils/issue-format-bot/lib/issueedit.js (hunk 1 above)
Comment (strugee) [reply utils/issue-format-bot/lib/issueedit.js]: @koops76 what's the difference, besides the quotes? I've consistently been using single quotes.

File: utils/issue-format-bot/test/mocks/context.js (hunk 2 above)
Comment (strugee) [reply utils/issue-format-bot/test/mocks/context.js]: I think `new Promise(noop)` makes it clearer what's going on - we're creating a new Promise that's a noop. Whereas with your example you have to know offhand what `Promise.resolve()` does.

File: utils/issue-format-bot/lib/issueedit.js (hunk 4 above)
Comment (strugee) [reply utils/issue-format-bot/lib/issueedit.js]: I did this originally but decided the other way made what was happening clearer. Your version is super dense :)

File: utils/issue-format-bot/test/mocks/context.js (hunk 2 above)
Comment (koops76) [reply utils/issue-format-bot/test/mocks/context.js]: `new Promise(noop)` never resolves since `resolve` is never called.

File: utils/issue-format-bot/lib/issueedit.js (hunk 1 above)
Comment (koops76) [reply utils/issue-format-bot/lib/issueedit.js]: It's ok to use double quotes to avoid escaping

File: utils/issue-format-bot/lib/issueedit.js (hunk 4 above)
Comment (koops76) [reply utils/issue-format-bot/lib/issueedit.js]: At least call it `allCommentsData`.

**Comment by Hainish** [comment]
Thanks, this looks good to me.  Merging and deploying fix now.
