### PR TITLE
Fixes for Firefox Developer Edition (resolves #4195)

### LINKED ISSUE #4195: HTTPS Everywhere is broken on Firefox Developer Edition
I am using 64-bit Firefox Developer Edition 46.0a2 (2016-02-20).

I installed HTTPS Everywhere from AMO, not EFF.org.

I have version 5.1.3.

The SSL Observatory option doesn't work in the toolbar icon, and neither does the about option. On top of that, all of the settings in the observatory (accessed through the about:addons menu) are broken and don't work.

Is this related to changes in how Firefox handles addons, or is this a bug?

If anybody can help me confirm I am not the only one having these issues, that would be great.

Feedback appreciated.

### PR DESCRIPTION
**Pull request by Hainish**
1. Refactor js one-liner to allow ssl observatory component to load
2. HTTPSEverywhere object can no longer be refernced directly from
   toolbar xul

### CODE REVIEW

File: src/components/ssl-observatory.js [hunk 1]
```diff
@@ -313,7 +313,12 @@ SSLObservatory.prototype = {
     function toHexString(charCode) {
       return ("0" + charCode.toString(16)).slice(-2);
     }
-    return [toHexString(h.charCodeAt(i)) for (i in h)].join("").toUpperCase();
+
+    var hexArr = [];
+    for (i in h){
+      hexArr.push(toHexString(h.charCodeAt(i)));
```
Comment (jsha) [inline src/components/ssl-observatory.js]: Have you tested this loop? Suggestion: run before and after the patch, look at submitted hex values from the logs for a known host (e.g. libssh.org), and make sure they are the same.

Comment (Hainish) [inline src/components/ssl-observatory.js]: Just checked - they are the same.

**Comment by cooperq** [comment]
LGTM

**Comment by jsha** [comment]
LGTM
