### PR TITLE
Normlise disabled site hostname and migrate stored list, fix #18451

### LINKED ISSUE #18451: Disable on site feature does not work on same site with/ without tailing dots
Type: code issue

### Platform
Firefox 69.0.1 on Ubuntu 19
HTTPS Everywhere 2019.6.27

### Steps to reproduce

1. Visit https://www.disabled-site-example.com./ (with tailing dots)
2. Disable HTTPSE via the extension popup
3. Visit http://www.disabled-site-example.com/ (without tailing dots)
4. Open popup, observe "Disable HTTPS Everywhere on this site" button is present

### Expected behaviour

4. Open popup, observe "Enable HTTPS Everywhere on this site" button is present

### Cause

Disabled site's hostname is not normalisd before being saved to extension storage. Sites with tailing dots are regarded as different, even they are not.

### PR DESCRIPTION
**Pull request by cschanaj**
### List related issues if any

- #18451

### CODE REVIEW

File: chromium/background-scripts/util.js [hunk 1]
```diff
@@ -60,6 +60,16 @@ function loadExtensionFile(url, returnType) {
   return xhr.responseText;
 }
 
+/**
+ * Remove tailing dots from hostname, e.g. "www.example.com."
+ */
+function getNormalisedHostname(hostname) {
```
Comment (pipboy96) [inline chromium/background-scripts/util.js]: Wouldn't this snippet do the same?

js```
hostname = hostname.replace(/\.+$/, '')
if (hostname === '') {
  hostname = '.'
}
```

Comment (cschanaj) [reply chromium/background-scripts/util.js]: Thanks for the suggestion, when `hostname` was initially empty, the behaviour of your snippet is sightly different. I would like to avoid a change of behaviour in this PR.

P.S. if benchmarks suggest using RegExp is more favourable, I am open to changing it (possible in another PR).

Comment (pipboy96) [reply chromium/background-scripts/util.js]: @cschanaj It is indeed a good idea to move this change into a follow-up PR.

**Comment by pipboy96** [comment]
I'm currently benchmarking multiple implementations of normalizer.

**Comment by pipboy96** [comment]
@cschanaj I finished my benchmark, the result is that speed differences are quite low, you may reproduce it with this code:

```js
'use strict'

function normalize (hostname) {
  while (hostname && hostname[hostname.length - 1] === '.' && hostname !== '.') {
    hostname = hostname.slice(0, -1)
  }
  return hostname
}

function normalize2 (hostname) {
  if (hostname !== '') {
    hostname = hostname.replace(/\.+$/, '')
    if (hostname === '') {
      hostname = '.'
    }
  }
  return hostname
}

function normalize3 (hostname) {
  if (hostname.length < 2) {
    return hostname
  }
  let pos = hostname.length - 1;
  while (hostname[pos] === '.' && pos > 0) {
    pos--
  }
  return hostname.slice(0, pos + 1)
}

const functions = [
  normalize,
  normalize2,
  normalize3,
]

const tests = [
  ['', ''],
  ['.', '.'],
  ['....................', '.'],
  ['aaaaaaaaaaaaaaaaaaaa', 'aaaaaaaaaaaaaaaaaaaa'],
  ['aaaaaaaaaaaaaaaaaaaa....................', 'aaaaaaaaaaaaaaaaaaaa'],
]

for (const func of functions) {
  console.log(`Currently testing ${func.name}:\n`)
  for (const [from, to] of tests) {
    const result = func(from)
    if (result === to) {
      console.log(`Success: normalize('${from}') == '${result}'`)
    } else {
      console.log(`Failure: normalize('${from}') == '${result}' (should be '${to}')`)
    }
  }
  console.log('\n---\n')
}

console.log(`Pre-heating all functions.\n`)

for (const func of functions) {
  let currentResult; // to prevent v8 from optimizing the call out

  for (const [from, to] of tests) {
    for (let i = 0; i < 1e7; i++) {
      currentResult = normalize(from)
    }
  }
}

console.log(`done!\n`)

for (const func of functions) {
  console.log(`Currently benchmarking ${func.name}:\n`)

  const start = performance.now()

  let currentResult; // to prevent v8 from optimizing the call out

  for (const [from, to] of tests) {
    for (let i = 0; i < 1e7; i++) {
      currentResult = normalize(from)
    }
  }

  const finish = performance.now() - start

  console.log(`took ${finish} msecs!\n`)
}
```

**Comment by cschanaj** [comment]
So I guess we will not modify the normalizer function here. @zoracon @Hainish would you please review this when you have time? Besides, we do not have a full release since June, is there any schedule for it? Important changes including #18263, #18153 are not yet released to public.

**Comment by zoracon** [comment]
> So I guess we will not modify the normalizer function here. @zoracon @Hainish would you please review this when you have time? Besides, we do not have a full release since June, is there any schedule for it? Important changes including #18263, #18153 are not yet released to public.

@cschanaj Thanks for bringing to my attention. Will review this and as far as the next release, I want to get one out October 14th. Thank you for your patience

**Comment by zoracon** [comment]
One more thing:
Thank you @cschanaj , @pipboy96 , @ivysrono , @J0WI, @TotalCaesar659, and @Bisaloo so much for taking down the number of PRs on the repo to a much more manageable state in the past few weeks. This is great work and I'm extremely grateful.

**Comment by zoracon** [comment]
closes #18451
